# Generated by Django 5.1.6 on 2025-02-10 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='algoriviewuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='algoriviewuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='algoriviewuser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='algoriviewuser',
            name='last_name',
        ),
    ]
