# Generated by Django 5.1.6 on 2025-02-10 13:30

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('type', models.SmallIntegerField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 2, 10, 22, 30, 25, 27440))),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('problem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.problem')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('start_line', models.SmallIntegerField()),
                ('end_line', models.SmallIntegerField()),
                ('history_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.history')),
            ],
        ),
    ]
