# Generated by Django 5.1.6 on 2025-02-11 06:49

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_alter_history_created_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feedback',
            new_name='Review',
        ),
        migrations.AddField(
            model_name='history',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='history',
            name='source_code',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='name',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='history',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 11, 15, 47, 57, 532022)),
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_code', models.TextField()),
                ('history_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.history')),
            ],
        ),
    ]
