# Generated by Django 5.1.6 on 2025-02-11 06:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_rename_feedback_review_history_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 11, 15, 49, 55, 559600)),
        ),
    ]
