# Generated by Django 5.1.6 on 2025-02-11 06:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_alter_history_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 11, 15, 56, 48, 209154)),
        ),
    ]
