# Generated by Django 5.1.6 on 2025-02-12 04:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_alter_history_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 12, 13, 28, 59, 134942)),
        ),
        migrations.AlterField(
            model_name='history',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
