# Generated by Django 5.1.6 on 2025-02-12 05:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0007_alter_history_created_at_alter_history_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 12, 14, 40, 0, 826767)),
        ),
        migrations.AlterField(
            model_name='problem',
            name='title',
            field=models.TextField(),
        ),
    ]
